Workaround my JGit/symlink issue
I was hitting the following, locally, after recent JGit upgrades (I had
to keep reverting back to 5.5.1.201910021850-r where I wasn't hitting
the issue):

    java.nio.file.FileAlreadyExistsException: /Users/dnw/.config
    	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:94) ~[?:?]
    	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
    	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
    	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
    	at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
    	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
    	at java.nio.file.Files.createDirectories(Files.java:742) ~[?:?]
    	at org.eclipse.jgit.util.SystemReader$Default.getXDGConfigHome(SystemReader.java:120) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.util.SystemReader$Default.openJGitConfig(SystemReader.java:131) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.util.SystemReader.getJGitConfig(SystemReader.java:348) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.util.SystemReader.getSystemConfig(SystemReader.java:373) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.util.SystemReader.getUserConfig(SystemReader.java:321) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:162) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:583) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:90) ~[org.eclipse.jgit-5.7.0.202003110725-r.jar:5.7.0.202003110725-r]
    	at sbtdynver.RepoStates$State.init(RepoStates.scala:39) ~[test-classes/:?]

The cause is my ~/.config is a symlink'd directory, for which the
default Files.createDirectories throws an exception.  Now (IIRC) there
was a fallback so it was "just" logging spam, but I grew tired of it.